import os

GIT_TIMEOUT_SECONDS = float(os.environ.get("FLUTTER_CRASH_ANALYZER_GIT_TIMEOUT_SECONDS", "30"))

DEFAULT_MAX_LOG_MATCHES = int(os.environ.get("FLUTTER_CRASH_ANALYZER_MAX_LOG_MATCHES", "50"))
