import os

FIREBASE_BIGQUERY_ACCESS_TOKEN = os.environ.get("FIREBASE_BIGQUERY_ACCESS_TOKEN")
FIREBASE_BIGQUERY_PROJECT = os.environ.get("FIREBASE_BIGQUERY_PROJECT")
FIREBASE_BIGQUERY_DATASET = os.environ.get("FIREBASE_BIGQUERY_DATASET", "firebase_crashlytics")
